### ISSUE TITLE
Alle Projekte anschauen

### ISSUE THREAD

**Issue by pommoisel** [pommoisel/LIT#7]
Möchte man sich ein Projekt in den Details anschauen hat man keinen Lektor und kriegt folgende Fehlermeldung :

**Couldn't find Gprod with 'id'=2 [WHERE "gprods"."lektor_id" = ?]**

**Comment by JPR13** [comment]
Wann genau hast du das Problem? Wenn mein User keinen Lektor zugewiesen hat kann ich mir problemlos alle Projekte im Detail angucken
